{
 "title": "adaptive-architecture",
 "time": { "from": "now-2m", "to": "now" },
 "panels": [
  {
   "title": "Producer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(producer_total_produced{instance=\"localhost:7774\",job=\"producer\"}[10s])",
     "legendFormat": "production rate actual"
    },
    {
     "expr": "producer_prod_rate_second{instance=\"localhost:7774\",job=\"producer\"}",
     "legendFormat": "production rate required"
    },
    {}
   ]
  },
  {
   "title": "Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(queue_total_enqueued{instance=\"localhost:7773\",job=\"queue\"}[10s])",
     "legendFormat": "enqueue rate"
    },
    {
     "expr": "rate(queue_total_dequeued{instance=\"localhost:7773\",job=\"queue\"}[10s])",
     "legendFormat": "dequeue rate"
    },
    {
     "expr": "queue_queue_size{instance=\"localhost:7773\",job=\"queue\"}",
     "legendFormat": "items in queue"
    }
   ]
  },
  {
   "title": "Client",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(client_events_pulled_count{instance=\"localhost:7775\",job=\"client\"}[10s])",
     "legendFormat": "events pulled"
    },
    {
     "expr": "rate(client_events_processed_count{instance=\"localhost:7775\",job=\"client\"}[10s])",
     "legendFormat": "events processed"
    },
    {
     "expr": "client_event_process_time{instance=\"localhost:7775\",job=\"client\"}*1000",
     "legendFormat": "process time millis"
    },
    {
     "expr": "client_pool_size{instance=\"localhost:7775\",job=\"client\"}",
     "legendFormat": "pool size"
    }
   ]
  },
  {
   "title": "Proxy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(proxy_total_requests{instance=\"localhost:7776\",job=\"proxy\"}[10s])",
     "legendFormat": "request rate"
    },
    {
     "expr": "rate(proxy_total_failed_requests{instance=\"localhost:7776\",job=\"proxy\"}[10s])",
     "legendFormat": "failed request rate"
    }
   ]
  },
  {
   "title": "Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_mean_resp_time_millis{instance=\"localhost:7777\",job=\"server\"}",
     "legendFormat": "resp time millis"
    },
    {
     "expr": "server_rate_limit_req_second{instance=\"localhost:7777\",job=\"server\"}",
     "legendFormat": "rate limit reqs/second"
    },
    {
     "expr": "server_resp_time_stddev{instance=\"localhost:7777\",job=\"server\"}",
     "legendFormat": "resp time stddev"
    },
    {
     "expr": "server_rate_limit_burst{instance=\"localhost:7777\",job=\"server\"}",
     "legendFormat": "rate limit burst"
    },
    {
     "expr": "server_percentage_reqs_fail{instance=\"localhost:7777\",job=\"server\"}",
     "legendFormat": "percentage reqs to fail"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "client_pool_size{instance=\"localhost:7775\",job=\"client\"}",
     "legendFormat": "pool size"
    }
   ]
  }
 ]
}